version: '2'
services:
  db:
    image: postgres:9.6
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
    - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
    - "5432:5432"
  cassandra:
    image: cassandra:2.1.9
    volumes:
    - ./cassandra/etc/cassandra-env.sh:/etc/cassandra/cassandra-env.sh:ro
    ports:
    - "9160:9160"
  keycloak:
    image: jboss/keycloak-postgres:3.2.0.Final
    environment:
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_USER: admin
      POSTGRES_DATABASE: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PORT_5432_TCP_ADDR: postgres
    ports:
      - "8080:8080"
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/data/sdsc-realm.json"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./keycloak/sdsc-realm.json:/data/sdsc-realm.json:ro
    links:
      - db:postgres
    restart: on-failure
  reverse-proxy:
    image: nginx:mainline-alpine
    volumes:
    - ./nginx/etc/default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - graph-typesystem
      - graph-mutation
      - graph-navigation
      - resource-manager
    ports:
    - "9000:80"
  graph-typesystem:
    image: graph-typesystem-service:$PLATFORM_VERSION
    links:
    - db
    - cassandra
    ports:
    - "9000"
    restart: on-failure
  graph-mutation:
    image: graph-mutation-service:$PLATFORM_VERSION
    links:
    - db
    - cassandra
    ports:
    - "9000"
    restart: on-failure
  graph-navigation:
    image: graph-navigation-service:$PLATFORM_VERSION
#    environment:
#      GRAPH_SCOPE_REMOTE_URL: http://graph-typesystem:9000/api/types
    links:
    - cassandra
    ports:
    - "9000"
    restart: on-failure
  graph-init:
    image: graph-init:$PLATFORM_VERSION
    environment:
      GRAPH_API_TYPES: http://graph-typesystem:9000/api/types
    depends_on:
      - graph-typesystem
    links:
    - graph-typesystem:graph-typesystem
  resource-manager:
    image: resource-manager-service:$PLATFORM_VERSION
    environment:
      PLAY_APPLICATION_SECRET: $PLAY_APPLICATION_SECRET
      RESOURCE_MANAGER_PUBLIC_KEY: $RESOURCE_MANAGER_PUBLIC_KEY
      RESOURCE_MANAGER_PRIVATE_KEY: $RESOURCE_MANAGER_PRIVATE_KEY
#      GRAPH_SCOPE_REMOTE_URL: http://graph-typesystem:9000/api/types
    links:
      - graph-typesystem
    ports:
    - "9000"
    restart: on-failure
  storage:
    image: storage-service:$PLATFORM_VERSION
    environment:
      PLAY_APPLICATION_SECRET: $PLAY_APPLICATION_SECRET
      RESOURCE_MANAGER_PUBLIC_KEY: $RESOURCE_MANAGER_PUBLIC_KEY
#      GRAPH_SCOPE_REMOTE_URL: http://graph-typesystem:9000/api/types
    links:
      - resources-manager
    ports:
    - "9000"
    restart: on-failure
  apispec:
    # prepare static site with `make apispec` beforehand
    image: nginx:mainline-alpine
    volumes:
    - ./target/apispec:/usr/share/nginx/html:ro
    ports:
    - "9001:80"
