branches:
  only:
  - master
language: scala
scala:
- '2.11.8'
script: sbt ++$TRAVIS_SCALA_VERSION test && bash ./.travis/check-code-formatting.sh

# caching suggestions from http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  - find $HOME/.sbt        -name "staging"              -print -exec rm -rfv {} +
