# API spec in YAML
swagger: '2.0'
info:
  title: Resource Manager API
  description: |
    Resource Manager API specification
  version: '0.0.1'
# the domain of the service
host: internal.datascience.ch
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api/resource-manager
produces:
  - application/json
consumes:
  - application/json
tags:
- name: 'Resource Manager'
  description: 'Resource Manager'
paths:
  /authorize:
    post:
      tags:
        - 'Resource Manager'
      summary: 'Authorize resource access'
      parameters:
      - in: body
        name: body
        description: 'Resource access request object'
        required: true
        schema:
          $ref: '#/definitions/AccessRequest'
      - in: header
        name: Authorization
        description: 'Bearer token'
        required: true
        type: string
      responses:
        200:
          description: 'ok'
        401:
          description: 'Authentication required'
definitions:
  AccessRequest:
    type: object
    required:
    - scope
    properties:
      permission_holder_id:
        type: integer
        format: int64
      scope:
        type: array
        items:
          $ref: '#/definitions/ScopeQualifier'
      extra_claims:
        type: object
        description: Custom claims added by the requesting service
  ScopeQualifier:
    type: string
    enum:
    - 'storage:read'
    - 'storage:write'
    - 'storage:create'
    - 'storage:bucket_create'
    title: ScopeQualifier
