# API spec in YAML
swagger: '2.0'
info:
  title: Storage API
  description: |
    Storage API specification
  version: '0.0.1'
# the domain of the service
host: internal.datascience.ch
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api/storage
produces:
  - application/json
consumes:
  - application/json
tags:
- name: 'Explorer'
  description: 'File explorer'
- name: 'IO'
  description: 'Perform I/O operations'
paths:
  /explore/{bucket_id}:
    get:
      tags:
      - 'Explorer'
      summary: 'Bucket metadata'
      description: 'Access bucket metadata'
      parameters:
      - name: Authorization
        in: header
        description: 'Bearer token'
        required: true
        type: string
      - name: bucket_id
        in: path
        description: 'Bucket graph id'
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: 'Ok'
        404:
          description: 'Bucket not found'
  /io/read:
    get:
      tags:
      - 'IO'
      summary: 'Read file'
      description: 'Read file specified in authorization bearer token'
      parameters:
      - name: Authorization
        in: header
        description: 'Bearer token (from authorization request)'
        required: true
        type: string
      responses:
        200:
          description: 'Successful read'
  /io/write:
    post:
      tags:
      - 'IO'
      summary: 'Write file'
      description: 'Read file specified in authorization bearer token'
      consumes:
      - octet/steam
      parameters:
      - name: Authorization
        in: header
        description: 'Bearer token (from authorization request)'
        required: true
        type: string
      - name: body
        in: body
        description: 'File content'
        required: true
        schema:
          type: string
          format: binary
      responses:
        200:
          description: 'Successful write'

definitions: {}